### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/AllAboutMe#17]
To gather feedback on the prototype we need to carry out using testing. 
- [ ] Understand what users think about the app
- [ ] Highlight any potential issues 
- [ ] See if there are any additional features that users want
- [ ] Ensure that the flow of the app is intuitive to the user

**Comment by nickpovey** [comment]
So just before I send this to the participation worker who can show this to the YP (young people), is there anything I've missed.




"Ok so the developers have come up with a super super basic rough sketch of it so far, and want some feedback. Here is the link to the app

https://www.figma.com/proto/UKAmSqRqidjcKDnWcOv4QUJ2/All-About-Me?scaling=contain&node-id=51%3A0&redirected=1

This should work on phones or laptops. 

The questions we need answered are

Would you prefer login with your facebook account or would you prefer to create a separate account? 

Do you think this app is better than the form you used to have? Why?

Do you feel that being able to choose the colour of your app, would really improve your user experience?"

**Comment by Jen-Harris** [comment]
Hey @nickpovey thanks for this 👍 

Can we just clarify when you say 'super super basic rough sketch' do you mean it's basic because it currently doesn't have functionality for the user or because you would like the design to be changed? Just so we're on the same page! 

In terms of the user interview when you set it up maybe say: 
"please sign in and work through the form. Say/write down everything that you're thinking so we can understand your experience!"
This is super important so we can pick up any opinions that aren't based on a specific question!

Then for the questions it might be useful to ask a two more: 
* Would you like to be able to sketch answers to some questions? 
* Is there any other comments you have on the overall app?

**Comment by nickpovey** [comment]
No I didn't say that because Im not happy with it, don't worry, I just
meant basic. I'll add those questions

On 29 Sep 2017 10:11 am, "Jen Harris" <notifications@github.com> wrote:

Hey @nickpovey <https://github.com/nickpovey> thanks for this 👍

Can we just clarify when you say 'super super basic rough sketch' do you
mean it's basic because it currently doesn't have functionality for the
user or because you would like the design to be changed? Just so we're on
the same page!

In terms of the user interview when you set it up maybe say:
"please sign in and work through the form. Say/write down everything that
you're thinking so we can understand your experience!"
This is super important so we can pick up any opinions that aren't based on
a specific question!

Then for the questions it might be useful to ask a two more:

   - Would you like to be able to sketch answers to some questions?
   - Is there any other comments you have on the overall app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FAC-11/AllAboutMe/issues/17#issuecomment-333074459>,
or mute
the thread

**Comment by Jen-Harris** [comment]
Thanks @nickpovey :sweat_smile: 
We were worried!!

**Comment by nickpovey** [comment]
So I've spoken to the participation worker. Her group meets this friday. She did speak to some other young people and some of them were un sure about having that much personal info on an app and wanted to be assured that it was secure with password protection and stuff. She also spotted some typos

It looks like a great start to me – there are a couple of spelling mistakes & grammar errors:
 
Page 9  - Psychotherapy – h is missing
 
Page 10 – What – needs a capital letter
 
Page 13 – strengths – add the s
 
Page 15 – replace “makes” with “helps” in questions about feeling safe & calm
 
Page 20 – can we take out “Adult” as the app should be suitable for any transition whether it’s CAMHS, stepping up from Tier 2 to Tier 3 CAMHS services or from a school counsellor etc.

**Comment by rebecacalvoquintero** [comment]
Thanks @nickpovey!! This is very useful. We will make sure in the final version there are no typos.

We are working on the login/sign up feature of the app. We are building it in a way that its very secure. So people don't have to worry about having their data hacked. :). We do understand the sensitivity or this data, so make it secure its our prior priority.

Please let us know if you have any questions :)

Thank you very very much for your input!! :)
